steps:
  # Build the container image
  # - name: "gcr.io/cloud-builders/docker"
  #   args: ["build", "-t", "gcr.io/opas-badminton-dev/opas", "."]
  # Use Kaniko cache instead
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
    - --destination=gcr.io/opas-badminton-dev/image
    - --cache=true
    - --cache-ttl=1h
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/opas-badminton-dev/opas"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "opas",
        "--image",
        "gcr.io/opas-badminton-dev/opas",
        "--memory",
        "512M",
        "--concurrency",
        "1",
        "--region",
        "us-central1",
        "--platform",
        "managed",
      ]
images:
  - gcr.io/opas-badminton-dev/opas
