steps:
  # Use Kaniko cache
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
    - --destination=gcr.io/opas-badminton-dev/opas
    - --cache=true
    - --cache-ttl=1h
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "opas",
        "--image",
        "gcr.io/opas-badminton-dev/opas",
        "--memory",
        "512M",
        "--concurrency",
        "1",
        "--region",
        "us-central1",
        "--platform",
        "managed",
      ]
