version: '3'

services:
  selenium:
    container_name: selenium
    build:
      context: .
      dockerfile: selenium.dockerfile
    tty: true
    volumes:
        - ./app:/app
    command: flask run --host 0.0.0.0
